# Generated by Django 3.1.5 on 2021-01-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('question_text',), name='unique_question'),
        ),
    ]
